server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://lmentorserver.mysql.database.azure.com:3306/lmentordb?useSSL=true&requireSSL=false
    username: lmentorAdmin@lmentorserver
    password: lmentorPassword01
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: true
        id:
          new_generator_mappings: false