server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/lmentordb?useSSL=true
    username: lmentorusername
    password: 138c99d8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: true
        id:
          new_generator_mappings: false