server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.64.2:3306/lmentordb?useSSL=false
    username: rachidba
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        id:
          new_generator_mappings: false