server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/lmentordbdev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

api:
  version: v1

swagger:
  enabled: true
  title: L'Mentor REST API
  description: L'Mentor
  useDefaultResponseMessages: false
  enableUrlTemplating: false
  deepLinking: true
  defaultModelsExpandDepth: 1
  defaultModelExpandDepth: 1
  displayOperationId: false
  displayRequestDuration: false
  filter: false
  maxDisplayedTags: 0
  showExtensions: false;

lmentor:
  security:
    jwt:
      tokenExpirationTime: 43800 # Number of minutes => 1 month
      refreshTokenExpTime: 131400 # 3 months
      tokenIssuer: http://lmentor.ma
      tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
