server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/lmentordbdev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: rachidbaaziz.contact@gmail.com
    password: gmailPassword-01
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

api:
  version: v1

swagger:
  enabled: true
  title: L'Mentor REST API
  description: L'Mentor
  useDefaultResponseMessages: false
  enableUrlTemplating: false
  deepLinking: true
  defaultModelsExpandDepth: 1
  defaultModelExpandDepth: 1
  displayOperationId: false
  displayRequestDuration: false
  filter: false
  maxDisplayedTags: 0
  showExtensions: false;

lmentor:
  security:
    jwt:
      tokenExpirationTime: 43800 # Number of minutes => 1 month
      refreshTokenExpTime: 131400 # 3 months
      tokenIssuer: http://lmentor.ma
      tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus


